/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AgendamentoTokenRouteImport } from './routes/agendamento.$token'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicHooksReminderRouteImport } from './routes/api/public/hooks/reminder'
import { Route as ApiPublicHooksReengagementRouteImport } from './routes/api/public/hooks/reengagement'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoTokenRoute = AgendamentoTokenRouteImport.update({
  id: '/agendamento/$token',
  path: '/agendamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksReminderRoute = ApiPublicHooksReminderRouteImport.update({
  id: '/api/public/hooks/reminder',
  path: '/api/public/hooks/reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksReengagementRoute =
  ApiPublicHooksReengagementRouteImport.update({
    id: '/api/public/hooks/reengagement',
    path: '/api/public/hooks/reengagement',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/hooks/reengagement': typeof ApiPublicHooksReengagementRoute
  '/api/public/hooks/reminder': typeof ApiPublicHooksReminderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/hooks/reengagement': typeof ApiPublicHooksReengagementRoute
  '/api/public/hooks/reminder': typeof ApiPublicHooksReminderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/hooks/reengagement': typeof ApiPublicHooksReengagementRoute
  '/api/public/hooks/reminder': typeof ApiPublicHooksReminderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/agendamento/$token'
    | '/api/chat'
    | '/api/public/hooks/reengagement'
    | '/api/public/hooks/reminder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/agendamento/$token'
    | '/api/chat'
    | '/api/public/hooks/reengagement'
    | '/api/public/hooks/reminder'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/agendamento/$token'
    | '/api/chat'
    | '/api/public/hooks/reengagement'
    | '/api/public/hooks/reminder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AgendamentoTokenRoute: typeof AgendamentoTokenRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicHooksReengagementRoute: typeof ApiPublicHooksReengagementRoute
  ApiPublicHooksReminderRoute: typeof ApiPublicHooksReminderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento/$token': {
      id: '/agendamento/$token'
      path: '/agendamento/$token'
      fullPath: '/agendamento/$token'
      preLoaderRoute: typeof AgendamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/reminder': {
      id: '/api/public/hooks/reminder'
      path: '/api/public/hooks/reminder'
      fullPath: '/api/public/hooks/reminder'
      preLoaderRoute: typeof ApiPublicHooksReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reengagement': {
      id: '/api/public/hooks/reengagement'
      path: '/api/public/hooks/reengagement'
      fullPath: '/api/public/hooks/reengagement'
      preLoaderRoute: typeof ApiPublicHooksReengagementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AgendamentoTokenRoute: AgendamentoTokenRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicHooksReengagementRoute: ApiPublicHooksReengagementRoute,
  ApiPublicHooksReminderRoute: ApiPublicHooksReminderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
